'use client'

import { useEffect, useMemo, useState } from 'react'
import {
  Bell, BriefcaseBusiness, CalendarDays, Check, ChevronDown, ChevronRight, ClipboardList,
  Compass, FileText, Headphones, House, Lightbulb, MapPin, Menu, Rocket, Search, Settings,
  ShieldCheck, Sparkles, Trophy, UserRound, UsersRound, X, Mail, Phone, MapPinned, Pencil,
  Plus, ExternalLink, Clock3, CheckCircle2, CircleAlert, LockKeyhole, SlidersHorizontal
} from 'lucide-react'

type IconType = typeof House
type View = 'dashboard' | 'profile' | 'opportunities' | 'requests' | 'applications' | 'projects' | 'mentor' | 'events' | 'notifications' | 'settings'

const navItems: { label: string; path: View; icon: IconType }[] = [
  { label: 'Dashboard', path: 'dashboard', icon: House }, { label: 'My Profile', path: 'profile', icon: UserRound },
  { label: 'Explore Opportunities', path: 'opportunities', icon: Rocket }, { label: 'My Requests', path: 'requests', icon: ClipboardList },
  { label: 'My Applications', path: 'applications', icon: FileText }, { label: 'My Projects', path: 'projects', icon: BriefcaseBusiness },
  { label: 'My Mentor', path: 'mentor', icon: UsersRound }, { label: 'Events & Activities', path: 'events', icon: CalendarDays },
  { label: 'Notifications', path: 'notifications', icon: Bell }, { label: 'Settings', path: 'settings', icon: Settings },
]
const categories = [['Innovation', Lightbulb, 'blue'], ['Startup', Rocket, 'green'], ['Major Project', Sparkles, 'purple'], ['Internship', BriefcaseBusiness, 'orange'], ['Research', Search, 'blue'], ['Mentorship', UsersRound, 'pink'], ['IPR', ShieldCheck, 'green'], ['Drone', Sparkles, 'purple'], ['AI / IoT', Sparkles, 'yellow'], ['Competitions', Trophy, 'pink']] as const
const opportunities = [
  { title: 'AI for Social Impact Hackathon', org: 'SUKHF', type: 'Competition', place: 'Online', date: 'Oct 15, 2026', icon: Trophy, tone: 'yellow' },
  { title: 'Research Internship – IoT', org: 'TechSphere Labs', type: 'Internship', place: 'Hyderabad', date: 'Oct 20, 2026', icon: BriefcaseBusiness, tone: 'blue' },
  { title: 'Smart City Idea Challenge', org: 'SUKHF', type: 'Innovation', place: 'Online', date: 'Nov 05, 2026', icon: Lightbulb, tone: 'green' },
  { title: 'Mentorship Program for Students', org: 'SUKHF', type: 'Mentorship', place: 'Online', date: 'Nov 01, 2026', icon: UsersRound, tone: 'pink' },
  { title: 'GreenTech Startup Accelerator', org: 'ImpactWorks', type: 'Startup', place: 'Bengaluru', date: 'Nov 12, 2026', icon: Rocket, tone: 'green' },
  { title: 'Women in Deep Tech Fellowship', org: 'TechSphere Labs', type: 'Research', place: 'Hybrid', date: 'Nov 18, 2026', icon: ShieldCheck, tone: 'blue' },
  { title: 'Campus Drone Innovation Sprint', org: 'SUKHF Labs', type: 'Innovation', place: 'Hyderabad', date: 'Dec 02, 2026', icon: Sparkles, tone: 'purple' },
]
const applications = [
  ['AI for Social Impact Hackathon', 'Competition', 'Selected', 'Oct 15, 2026'], ['Research Internship – IoT', 'Internship', 'Under Review', 'Oct 20, 2026'], ['Smart City Idea Challenge', 'Innovation', 'Shortlisted', 'Nov 05, 2026'], ['GreenTech Startup Program', 'Startup', 'Rejected', 'Sep 28, 2026']
]
const requests = [['Need a Mentor for AI Project', 'Mentorship', 'Under Review', 'Sep 20, 2026'], ['Request for Internship Guidance', 'Guidance', 'Approved', 'Sep 10, 2026'], ['Request for IPR Support', 'IPR', 'Pending', 'Sep 05, 2026']]
const projects = [['Smart Attendance System', 'Academic Project', 'In Progress', 'May 2026 – Aug 2026'], ['AI Chatbot for Student Support', 'Personal Project', 'Completed', 'Jan 2026 – Apr 2026']]
const notifications = [['Your application has been shortlisted', 'Smart City Idea Challenge', '2 hours ago', 'success'], ['New opportunity added', 'Research Internship – IoT', '1 day ago', 'info'], ['Mentor meeting scheduled', 'With Dr. Ayesha Khan', '2 days ago', 'info'], ['Event reminder', 'Innovation & Startup Talk', '3 days ago', 'warning']]

function pathToView() { const path = window.location.pathname.replace(/^\//, '') as View; return navItems.some((item) => item.path === path) ? path : 'dashboard' }
function navigate(view: View) { window.history.pushState({}, '', view === 'dashboard' ? '/' : `/${view}`); window.dispatchEvent(new PopStateEvent('popstate')) }

export default function Page() {
  const [view, setView] = useState<View>('dashboard'); const [query, setQuery] = useState(''); const [menuOpen, setMenuOpen] = useState(false); const [profileMenu, setProfileMenu] = useState(false)
  const [applied, setApplied] = useState<string[]>([]); const [category, setCategory] = useState('All'); const [unread, setUnread] = useState(3); const [editing, setEditing] = useState(false)
  useEffect(() => { const sync = () => setView(pathToView()); setView(pathToView()); window.addEventListener('popstate', sync); return () => window.removeEventListener('popstate', sync) }, [])
  const go = (next: View) => { navigate(next); setView(next); setMenuOpen(false) }
  const filtered = useMemo(() => opportunities.filter((item) => `${item.title} ${item.org} ${item.type}`.toLowerCase().includes(query.toLowerCase()) && (category === 'All' || item.type === category)), [query, category])
  return <div className="dashboard-shell"><Sidebar active={view} go={go} menuOpen={menuOpen} close={() => setMenuOpen(false)} unread={unread} /><main className="main-area"><header className="topbar"><button className="menu-button" onClick={() => setMenuOpen(true)} aria-label="Open menu"><Menu /></button><div className="search-wrap"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search opportunities, events, mentors..." aria-label="Search" /></div><div className="top-actions"><button className="icon-button" aria-label="Open notifications" onClick={() => go('notifications')}><Bell /><i /></button><div className="profile-menu"><div className="avatar">N</div><div className="profile-copy"><strong>Nuzhath</strong><span>Student</span></div><button aria-label="Open profile menu" onClick={() => setProfileMenu(!profileMenu)}><ChevronDown /></button>{profileMenu && <div className="profile-dropdown"><button onClick={() => go('profile')}>View profile</button><button onClick={() => setProfileMenu(false)}>Sign out</button></div>}</div></div></header><div className="content">{view === 'dashboard' && <Dashboard go={go} category={category} setCategory={setCategory} filtered={filtered} applied={applied} setApplied={setApplied} />}{view === 'profile' && <Profile editing={editing} setEditing={setEditing} />}{view === 'opportunities' && <Opportunities filtered={filtered} category={category} setCategory={setCategory} applied={applied} setApplied={setApplied} />}{view === 'requests' && <ListView title="My Requests" subtitle="Track the requests you have raised." action="New Request" rows={requests} type="request" />}{view === 'applications' && <ListView title="My Applications" subtitle="Track the status of your opportunity applications." rows={applications} type="application" />}{view === 'projects' && <Projects />}{view === 'mentor' && <Mentor />}{view === 'events' && <Events />}{view === 'notifications' && <Notifications unread={unread} setUnread={setUnread} />}{view === 'settings' && <SettingsView />}</div></main></div>
}

function Sidebar({ active, go, menuOpen, close, unread }: { active: View; go: (v: View) => void; menuOpen: boolean; close: () => void; unread: number }) { return <aside className={`sidebar ${menuOpen ? 'sidebar-open' : ''}`}><div className="brand"><div className="brand-mark"><span /><span /><span /></div><div><strong>SUKHF</strong><small>Innovation & Opportunity<br />Management Platform</small></div><button className="mobile-close" onClick={close} aria-label="Close menu"><X /></button></div><nav className="nav-list" aria-label="Primary navigation">{navItems.map(({ label, path, icon: Icon }) => <button key={path} className={`nav-item ${active === path ? 'active' : ''}`} onClick={() => go(path)}><Icon /><span>{label}</span>{path === 'notifications' && <b className="notif-count">{unread}</b>}</button>)}</nav><div className="sidebar-quote"><p>Learn<br />Build<br />Collaborate<br />Create Impact</p><span>—</span><div className="quote-leaves">✦</div></div><footer>© 2026 SUKHF<br />All rights reserved.</footer></aside> }
function PageIntro({ eyebrow = 'STUDENT PORTAL', title, subtitle, action }: { eyebrow?: string; title: string; subtitle: string; action?: React.ReactNode }) { return <div className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subtitle">{subtitle}</p></div>{action}</div> }
function Panel({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="panel"><div className="section-heading"><h2>{title}</h2>{action}</div>{children}</section> }
function Dashboard({ go, category, setCategory, filtered, applied, setApplied }: any) { return <><section className="welcome-row"><div><p className="eyebrow">STUDENT PORTAL</p><h1>Welcome back, Nuzhath!</h1><p className="subtitle">Explore opportunities, collaborate with mentors and build your journey with SUKHF.</p></div><div className="quote-card"><span>“</span><em>Opportunities don’t happen,<br />you create them.</em><small>— SUKHF</small></div></section><section className="stats-grid">{[['3', 'My Requests', 'requests', ClipboardList, 'blue'], ['5', 'My Applications', 'applications', Rocket, 'green'], ['2', 'My Projects', 'projects', Sparkles, 'purple'], ['1', 'My Mentor', 'mentor', UsersRound, 'orange']].map(([n, label, path, Icon, tone]: any) => <button className={`stat-card ${tone}`} key={label} onClick={() => go(path)}><span className="stat-icon"><Icon /></span><span><strong>{n}</strong><small>{label}</small></span><ChevronRight /></button>)}<div className="completion-card"><div className="progress-ring"><span>80%</span></div><div><strong>Profile Completion</strong><p>Complete your profile to get<br />better recommendations.</p><button onClick={() => go('profile')}>Complete Profile</button></div></div></section><Panel title="Explore Opportunity Categories" action={<button onClick={() => go('opportunities')}>View All</button>}><div className="category-grid">{categories.map(([label, Icon, tone]: any) => <button className={`category-card ${tone} ${category === label ? 'selected' : ''}`} key={label} onClick={() => setCategory(category === label ? 'All' : label)}><Icon /><span>{label}</span></button>)}</div></Panel><div className="two-column"><OpportunityPanel filtered={filtered} applied={applied} setApplied={setApplied} go={go} /><Panel title="My SUKHF Journey" action={<button onClick={() => go('applications')}>View Details</button>}><Journey /></Panel></div><div className="bottom-grid"><Panel title="Upcoming Events" action={<button onClick={() => go('events')}>View All</button>}><EventRows compact /></Panel><Panel title="Latest Announcements" action={<button onClick={() => go('notifications')}>View All</button>}><AnnouncementRows /></Panel><Panel title="Need Help?"><div className="help-content"><span><Headphones /></span><div><p>Have questions or need guidance?<br />Reach out to our support team.</p><button onClick={() => go('mentor')}>Contact Support</button></div></div></Panel></div></> }
function OpportunityPanel({ filtered, applied, setApplied, go }: any) { return <Panel title="Recommended Opportunities" action={<button onClick={() => go('opportunities')}>View All</button>}><div className="opportunity-list">{filtered.slice(0, 5).map((item: any) => <OpportunityRow key={item.title} item={item} applied={applied} setApplied={setApplied} />)}</div></Panel> }
function OpportunityRow({ item, applied, setApplied }: any) { const Icon = item.icon; return <div className="opportunity"><span className={`opportunity-icon ${item.tone}`}><Icon /></span><div className="opportunity-info"><strong>{item.title}</strong><span>{item.org}</span><div><b>{item.type}</b><small><MapPin />{item.place}</small><small><CalendarDays />{item.date}</small></div></div><button className="apply-button" onClick={() => setApplied((current: string[]) => current.includes(item.title) ? current : [...current, item.title])}>{applied.includes(item.title) ? 'Applied' : 'Apply'}</button></div> }
function Opportunities({ filtered, category, setCategory, applied, setApplied }: any) { return <><PageIntro title="Explore Opportunities" subtitle="Find the right opportunities to learn, build and grow." action={<button className="primary-button"><SlidersHorizontal /> Filter</button>} /><Panel title="All Opportunities" action={<span className="result-count">{filtered.length} opportunities</span>}><div className="filter-row"><button className={category === 'All' ? 'filter-chip active' : 'filter-chip'} onClick={() => setCategory('All')}>All Categories</button>{['Competition', 'Internship', 'Innovation', 'Mentorship'].map((item) => <button className={category === item ? 'filter-chip active' : 'filter-chip'} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="opportunity-list large-list">{filtered.map((item: any) => <OpportunityRow key={item.title} item={item} applied={applied} setApplied={setApplied} />)}</div></Panel></> }
function Profile({ editing, setEditing }: any) { const [saved, setSaved] = useState(false); return <><PageIntro title="My Profile" subtitle="Manage your personal information and showcase your skills." action={<button className="primary-button" onClick={() => { setEditing(!editing); setSaved(false) }}>{editing ? 'Cancel' : 'Edit Profile'}</button>} /><div className="profile-layout"><Panel title="Profile overview"><div className="profile-card"><div className="large-avatar">N</div><h2>Nuzhath</h2><p>Student</p><span><Mail /> nuzhath@example.com</span><span><Phone /> +91 98765 43210</span><span><MapPinned /> Hyderabad, India</span><div className="mini-progress"><span style={{ width: '80%' }} /></div><small>Profile Completion <b>80%</b></small></div></Panel><Panel title="Personal information"><div className="tabs"><button className="active">Personal Info</button><button>Academic Details</button><button>Skills & Interests</button><button>Documents</button></div><div className="form-grid">{[['Full Name', 'Nuzhath'], ['Date of Birth', '12 Mar 2005'], ['Gender', 'Female'], ['Email', 'nuzhath@example.com'], ['Phone', '+91 98765 43210'], ['Location', 'Hyderabad, India']].map(([label, value]) => <label key={label}>{label}<input disabled={!editing} defaultValue={value} /></label>)}</div><label className="full-field">Bio<textarea disabled={!editing} defaultValue="Passionate about technology, innovation and social impact. Looking forward to learning and contributing through SUKHF opportunities." /></label><div className="interest-row"><strong>Interests</strong>{['AI / ML', 'Web Development', 'Social Impact', 'Research', 'Startups'].map((item) => <span key={item}>{item}</span>)}<button><Plus /> Add</button></div>{editing && <button className="primary-button save-button" onClick={() => { setSaved(true); setEditing(false) }}>{saved ? 'Saved' : 'Save Changes'}</button>}</Panel></div></> }
function ListView({ title, subtitle, action, rows, type }: any) { return <><PageIntro title={title} subtitle={subtitle} action={action && <button className="primary-button"><Plus />{action}</button>} /><Panel title={title} action={<div className="tabs compact"><button className="active">All ({rows.length})</button><button>Pending</button><button>Completed</button></div>}><div className="data-list">{rows.map((row: string[]) => <div className="data-row" key={row[0]}><span className={`row-icon ${type === 'request' ? 'orange' : 'blue'}`}>{type === 'request' ? <ClipboardList /> : <FileText />}</span><div><strong>{row[0]}</strong><small>{row[1]}</small></div><Status text={row[2]} /><small>{row[3]}</small><button className="ghost-button">View <ExternalLink /></button></div>)}</div></Panel></> }
function Status({ text }: { text: string }) { return <span className={`status ${text.toLowerCase().replaceAll(' ', '-')}`}>{text}</span> }
function Projects() { return <><PageIntro title="My Projects" subtitle="Manage and track your projects." action={<button className="primary-button"><Plus /> New Project</button>} /><div className="summary-grid"><div><strong>2</strong><span>Total Projects</span></div><div><strong>1</strong><span>In Progress</span></div><div><strong>1</strong><span>Completed</span></div></div><Panel title="Your projects"><div className="data-list">{projects.map((row) => <div className="data-row" key={row[0]}><span className="row-icon purple"><Sparkles /></span><div><strong>{row[0]}</strong><small>{row[1]}</small></div><Status text={row[2]} /><small>{row[3]}</small><button className="ghost-button">View <ExternalLink /></button></div>)}</div></Panel></> }
function Mentor() { return <><PageIntro title="My Mentor" subtitle="Connect and learn with your mentor." /><div className="mentor-grid"><Panel title="Your mentor"><div className="mentor-card"><div className="mentor-avatar">AK</div><div><h2>Dr. Ayesha Khan</h2><p>Faculty Mentor<br />AI & Machine Learning</p><div className="mentor-actions"><button className="primary-button"><Mail /> Email</button><button className="secondary-button"><CalendarDays /> Schedule Meeting</button></div></div></div></Panel><Panel title="Mentorship progress"><div className="mentor-progress"><div className="progress-ring small"><span>80%</span></div><div><strong>3 of 5 milestones completed</strong><div className="bar"><span style={{ width: '60%' }} /></div></div></div></Panel></div><Panel title="Upcoming meetings"><EventRows /></Panel></> }
function Events() { return <><PageIntro title="Events & Activities" subtitle="Stay updated with upcoming events, workshops and activities." /><Panel title="Upcoming events" action={<div className="tabs compact"><button className="active">Upcoming (3)</button><button>Past (5)</button></div>}><EventRows /></Panel></> }
function EventRows({ compact = false }: { compact?: boolean }) { const items = [['SEP', '28', 'Innovation & Startup Talk', '10:00 AM – 12:00 PM', 'Online'], ['OCT', '05', 'Drone Technology Workshop', '10:00 AM – 02:00 PM', 'Hyderabad'], ['OCT', '12', 'IPR Awareness Session', '02:00 PM – 04:00 PM', 'Online']]; return <div className="event-list">{items.slice(0, compact ? 2 : 3).map((item) => <div className="event" key={item[2]}><time><b>{item[0]}</b><strong>{item[1]}</strong></time><div><strong>{item[2]}</strong><span>SUKHF</span><small><CalendarDays />{item[3]} <MapPin />{item[4]}</small></div><button className="ghost-button">{compact ? <ChevronRight /> : 'Register'}</button></div>)}</div> }
function AnnouncementRows() { return <div>{['Applications Open for IGNITE 2026', 'New Research Opportunities Added', 'Mentorship Program Applications Live'].map((item, index) => <div className="announcement" key={item}><span className="announcement-icon"><Bell /></span><strong>{item}</strong><small>Sep {20 - index * 2}, 2026</small></div>)}</div> }
function Notifications({ unread, setUnread }: any) { return <><PageIntro title="Notifications" subtitle="Stay updated with the latest updates." action={<button className="secondary-button" onClick={() => setUnread(0)}>Mark all as read</button>} /><Panel title="Your notifications" action={<div className="tabs compact"><button className="active">All</button><button>Unread ({unread})</button></div>}><div className="notification-list">{notifications.map((item) => <div className={`notification-row ${item[3]}`} key={item[0]}><span className="notification-icon"><Bell /></span><div><strong>{item[0]}</strong><small>{item[1]}</small></div><time>{item[2]}</time><button className="ghost-button">View</button></div>)}</div></Panel></> }
function SettingsView() { const [toggles, setToggles] = useState([true, false, true]); return <><PageIntro title="Settings" subtitle="Manage your account preferences." /><div className="settings-layout"><Panel title="Account settings"><div className="settings-list">{[['Email Notifications', 'Receive updates about applications, events and messages.', Bell], ['Marketing Updates', 'Receive newsletters and platform updates.', Sparkles], ['Push Notifications', 'Get alerts directly on your device.', Bell]].map(([title, desc, Icon], index) => <div className="setting-row" key={title as string}><span className="setting-icon"><Icon /></span><div><strong>{title as string}</strong><small>{desc as string}</small></div><button className={`toggle ${toggles[index] ? 'on' : ''}`} onClick={() => setToggles((current) => current.map((value, i) => i === index ? !value : value))} aria-label={`Toggle ${title}`}><i /></button></div>)}</div></Panel><Panel title="Privacy & security"><div className="settings-list"><div className="setting-row"><span className="setting-icon"><LockKeyhole /></span><div><strong>Change password</strong><small>Update your account password regularly.</small></div><button className="secondary-button">Update</button></div><div className="setting-row"><span className="setting-icon"><ShieldCheck /></span><div><strong>Two-factor authentication</strong><small>Add an extra layer of security to your account.</small></div><button className="secondary-button">Set up</button></div></div></Panel></div></> }
function Journey() { return <><div className="journey-track">{['Profile Completed', 'Applied', 'Selected', 'In Progress', 'Evaluation', 'Completed'].map((step, index) => <div className={`journey-step ${index < 2 ? 'done' : index === 2 ? 'current' : ''}`} key={step}><span>{index < 2 ? <Check /> : ''}</span><small>{step}</small></div>)}</div><div className="journey-banner"><img className="journey-image" src="/sukhf-journey.png" alt="Student building an innovation project" /><div><strong>You are on your way!</strong><p>Keep exploring, applying and learning.<br />Your journey with SUKHF has just begun.</p></div></div></> }
